In [1]:
#First, create a maze generator
# Demands for this generator:
# 1. needs to have entrance and exit
# 2. a path should ways have at least one adjacent path tile

import pandas as pd
import numpy as np

In [16]:
def MazeGenerator(width, height):
    maze = pd.DataFrame(np.random.randint(0,2, size = (height,width)))
    return maze

In [19]:
MazeGenerator(10, 10)

   0  1  2  3  4  5  6  7  8  9
0  1  0  1  1  1  0  1  1  0  0
1  0  0  0  1  0  1  1  0  1  0
2  0  0  1  0  0  1  1  1  1  1
3  1  0  1  1  1  1  1  0  0  1
4  1  0  0  1  1  0  0  1  0  0
5  1  0  0  1  1  1  1  1  0  1
6  0  0  1  0  1  1  1  0  1  0
7  0  1  1  0  1  1  1  1  0  1
8  1  1  1  1  0  0  1  1  0  1
9  1  1  0  0  1  1  1  0  1  1

In [15]:
np.random.randint(0,2, size = (4,4))

array([[1, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 1]])